algoritmo "semnome"
// Função :
// Autor :
// Data : 06/09/2022
// Seção de Declarações 
var
codigo : inteiro
inicio
// Seção de Comandos 
escreva("Informe o código: ")
leia(codigo)

se(codigo=1)entao
   escreva("Produto: Sorvete")
fimse

se(codigo=2)entao
   escreva("Produto: Sundae")
fimse

se(codigo=3)entao
   escreva("Produto: Picolé")
fimse

se(codigo=4)entao
   escreva("Produto: Açaí")
fimse

fimalgoritmo
