algoritmo "semnome"
// Função :
// Autor :
// Data : 09/06/2022
// Seção de Declarações 
var

p : real

inicio
// Seção  Comandos

//p <- 2\2

//escreva(p)

escreval(2\3*4)
//PRIORIZANDO DIV INTEIRA EM CIMA DA DIVISÃO e mult

escreval("etapa: ",3*2\4)
escreval("etapa2: ",3/3\6)
escreval("etapa2: ",3\2/3)
//OBS: não dividir antes de capturar a div inteira

escreval(2\2)
escreval(1\2)

escreval("calc errado: ",4+3/3*2\2)
escreval("calc certo: ",4+2\2*3/3)

escreval(6\7)

fimalgoritmo
